
import './globals.css';
import type { Metadata } from "next";

import { AuthProvider } from '@/contexts/AuthContext';
import { MarketsProvider } from '@/contexts/MarketsContext';

export const metadata: Metadata = {
  title: "MK Matka Booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <AuthProvider>
          <MarketsProvider>
            {children}
          </MarketsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
