
import './globals.css';
import type { Metadata } from "next";

import { GlobalProvider } from '@/contexts/GlobalContext';
import { MarketsProvider } from '@/contexts/MarketsContext';
import Header from './components/Header';

export const metadata: Metadata = {
  title: "MK Matka Booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <GlobalProvider>
          <MarketsProvider>
            {/* <SplashScreenWrapper> */}
            <Header />
            {children}
            {/* </SplashScreenWrapper> */}
          </MarketsProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
